// <auto-generated />
using System;
using EnglishEducomics.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EnglishEducomics.Migrations
{
    [DbContext(typeof(EnglishEducomicsContext))]
    partial class EnglishEducomicsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EnglishEducomics.Models.Answer", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<bool>("IsCorrectOption");

                    b.Property<Guid>("QuestionID");

                    b.HasKey("ID");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("EnglishEducomics.Models.Course", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Syllabus");

                    b.HasKey("ID");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("EnglishEducomics.Models.Lesson", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<bool>("IsComplete");

                    b.Property<string>("Name");

                    b.Property<Guid>("ObjectiveID");

                    b.HasKey("ID");

                    b.ToTable("Lesson");
                });

            modelBuilder.Entity("EnglishEducomics.Models.Objective", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CourseID");

                    b.Property<bool>("IsMastered");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Objective");
                });

            modelBuilder.Entity("EnglishEducomics.Models.Question", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<bool>("IsMastered");

                    b.Property<Guid>("ObjectiveID");

                    b.HasKey("ID");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("EnglishEducomics.Models.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateJoined");

                    b.Property<string>("Email");

                    b.Property<int>("InitialLevel");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
